Fuzzol code + afl-plot + python plot

diff --git a/afl-plot b/afl-plot
--- a/afl-plot
+++ b/afl-plot
@@ -17,8 +17,8 @@
 
 echo "progress plotting utility for afl-fuzz by <lcamtuf@google.com>"
 echo
-
-if [ ! "$#" = "2" ]; then
+echo "$#"
+if [ ! "$#" = "6" ]; then
 
   cat 1>&2 <<_EOF_
 This program generates gnuplot images from afl-fuzz output data. Usage:
@@ -43,7 +43,7 @@ if [ "$AFL_ALLOW_TMP" = "" ]; then
   echo "$1" | grep -qE '^(/var)?/tmp/'
   T1="$?"
 
-  echo "$2" | grep -qE '^(/var)?/tmp/'
+  echo "$5" | grep -qE '^(/var)?/tmp/'
   T2="$?"
 
   if [ "$T1" = "0" -o "$T2" = "0" ]; then
@@ -75,17 +75,17 @@ if [ "$GNUPLOT" = "" ]; then
 
 fi
 
-mkdir "$2" 2>/dev/null
+mkdir "$5" 5>/dev/null
 
-if [ ! -d "$2" ]; then
+if [ ! -d "$5" ]; then
 
   echo "[-] Error: unable to create the output directory - pick another location." 1>&2
   exit 1
 
 fi
 
-rm -f "$2/high_freq.png" "$2/low_freq.png" "$2/exec_speed.png"
-mv -f "$2/index.html" "$2/index.html.orig" 2>/dev/null
+rm -f "$5/high_freq.png" "$2/low_freq.png" "$5/exec_speed.png"
+mv -f "$5/index.html" "$5/index.html.orig" 5>/dev/null
 
 echo "[*] Generating plots..."
 
@@ -94,11 +94,13 @@ echo "[*] Generating plots..."
 cat <<_EOF_
 set terminal png truecolor enhanced size 1000,300 butt
 
-set output '$2/high_freq.png'
+set output '$5/high_freq.png'
 
 set xdata time
+set xlabel 'time'
+set ylabel 'interesting paths'
 set timefmt '%s'
-set format x "%b %d\n%H:%M"
+set format x "%H:%M"
 set tics font 'small'
 unset mxtics
 unset mytics
@@ -112,49 +114,62 @@ set key outside
 set autoscale xfixmin
 set autoscale xfixmax
 
-plot '$1/plot_data' using 1:4 with filledcurve x1 title 'total paths' linecolor rgb '#000000' fillstyle transparent solid 0.2 noborder, \\
-     '' using 1:3 with filledcurve x1 title 'current path' linecolor rgb '#f0f0f0' fillstyle transparent solid 0.5 noborder, \\
-     '' using 1:5 with lines title 'pending paths' linecolor rgb '#0090ff' linewidth 3, \\
-     '' using 1:6 with lines title 'pending favs' linecolor rgb '#c00080' linewidth 3, \\
-     '' using 1:2 with lines title 'cycles done' linecolor rgb '#c000f0' linewidth 3
+plot '$1/plot_data' using 1:4 with lines title ' Fuzzol total paths' linecolor rgb '#fb8761' linewidth 3, \\
+     '$2/plot_data' using 1:4 with lines title 'Superion total paths' linecolor rgb '#21908d' linewidth 3, \\
+     '$3/plot_data' using 1:4 with lines title 'AFL Fast total paths' linecolor rgb '#0090ff' linewidth 3, \\
+     '$4/plot_data' using 1:4 with lines title 'MOpt total paths' linecolor rgb '#c00080' linewidth 3
 
-set terminal png truecolor enhanced size 1000,200 butt
-set output '$2/low_freq.png'
+set terminal png truecolor enhanced size 1000,300 butt
+set output '$5/low_freq.png'
 
-plot '$1/plot_data' using 1:8 with filledcurve x1 title '' linecolor rgb '#c00080' fillstyle transparent solid 0.2 noborder, \\
-     '' using 1:8 with lines title ' uniq crashes' linecolor rgb '#c00080' linewidth 3, \\
-     '' using 1:9 with lines title 'uniq hangs' linecolor rgb '#c000f0' linewidth 3, \\
-     '' using 1:10 with lines title 'levels' linecolor rgb '#0090ff' linewidth 3
+set xdata time
+set xlabel 'time'
+set ylabel 'crashes'
+set timefmt '%s'
+set format x "%H:%M"
+set tics font 'small'
+set xtics font ",9"
+set ytics font ", 9"
 
-set terminal png truecolor enhanced size 1000,200 butt
-set output '$2/exec_speed.png'
+set grid xtics linetype 0 linecolor rgb '#e0e0e0'
+set grid ytics linetype 0 linecolor rgb '#e0e0e0'
+set border linecolor rgb '#50c0f0'
+set tics textcolor rgb '#000000'
+set key outside
 
-plot '$1/plot_data' using 1:11 with filledcurve x1 title '' linecolor rgb '#0090ff' fillstyle transparent solid 0.2 noborder, \\
-     '$1/plot_data' using 1:11 with lines title '    execs/sec' linecolor rgb '#0090ff' linewidth 3 smooth bezier;
+
+set autoscale xfixmin
+set autoscale xfixmax
+
+
+plot '$1/plot_data' using 1:8 with lines title ' Fuzzol crashes' linecolor rgb '#fb8761' linewidth 3, \\
+     '$2/plot_data' using 1:8 with lines title 'Superion crashes' linecolor rgb '#21908d' linewidth 3, \\
+     '$3/plot_data' using 1:8 with lines title 'AFL Fast crashes' linecolor rgb '#0090ff' linewidth 3, \\
+     '$4/plot_data' using 1:8 with lines title 'MOpt crashes' linecolor rgb '#c00080' linewidth 3
+
 
 _EOF_
 
 ) | gnuplot 
 
-if [ ! -s "$2/exec_speed.png" ]; then
+#if [ ! -s "$5/exec_speed.png" ]; then
 
-  echo "[-] Error: something went wrong! Perhaps you have an ancient version of gnuplot?" 1>&2
-  exit 1
+#  echo "[-] Error: something went wrong! Perhaps you have an ancient version of gnuplot?" 1>&2
+#  exit 1
 
-fi
+#fi
 
 echo "[*] Generating index.html..."
 
-cat >"$2/index.html" <<_EOF_
+cat >"$5/index.html" <<_EOF_
 <table style="font-family: 'Trebuchet MS', 'Tahoma', 'Arial', 'Helvetica'">
-<tr><td style="width: 18ex"><b>Banner:</b></td><td>$BANNER</td></tr>
-<tr><td><b>Directory:</b></td><td>$1</td></tr>
+<tr><td><b>Compiler Version:</b></td><td>$6</td></tr>
 <tr><td><b>Generated on:</b></td><td>`date`</td></tr>
 </table>
 <p>
 <img src="high_freq.png" width=1000 height=300><p>
-<img src="low_freq.png" width=1000 height=200><p>
-<img src="exec_speed.png" width=1000 height=200>
+<img src="low_freq.png" width=1000 height=300><p>
+
 
 _EOF_
 
@@ -162,9 +177,17 @@ _EOF_
 # served by Apache or other HTTP daemon. Since the plots aren't horribly
 # sensitive, this seems like a reasonable trade-off.
 
-chmod 755 "$2"
-chmod 644 "$2/high_freq.png" "$2/low_freq.png" "$2/exec_speed.png" "$2/index.html"
+chmod 755 "$5"
+chmod 755 " $5/high_freq.png" "$5/low_freq.png" "$5/index.html"
 
 echo "[+] All done - enjoy your charts!"
 
 exit 0
+
+
+#./afl-plot /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1myFuzzer/ /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1Superion/ /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1AFLFAST/ /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1Mopt/ out6 v0.7.1
+
+#./afl-plot /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1myFuzzer/ /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1Superion/ /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1AFLFAST/ /home/harry/Documents/RESULTS/allFuzzers/v7.1/0.7.1Mopt/ out2 v0.7.1
+
+#./afl-plot /home/harry/Documents/RESULTS/allFuzzers/v7.4/0.7.4fuzzol/ /home/harry/Documents/RESULTS/allFuzzers/v7.4/0.7.4Superion/ /home/harry/Documents/RESULTS/allFuzzers/v7.4/0.7.4AFLFAST/ /home/harry/Documents/RESULTS/allFuzzers/v7.4/0.7.4Mopt/ out2 v0.7.4
+
